<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWhk99c8\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWhk99c8/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWhk99c8.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWhk99c8\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWhk99c8\appProdProjectContainer([
    'container.build_hash' => 'Whk99c8',
    'container.build_id' => 'f204444f',
    'container.build_time' => 1613985907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWhk99c8');
