<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUcw2jmi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUcw2jmi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUcw2jmi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUcw2jmi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUcw2jmi\appProdProjectContainer([
    'container.build_hash' => 'Ucw2jmi',
    'container.build_id' => '67e0178c',
    'container.build_time' => 1614006369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUcw2jmi');
